version: '2'
services:
  db:
    image: mysql:5.7.11
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/mastools
    ports:
      - "3000:3000"
    depends_on:
      - db
